[tool.poetry]
name = "pypgsync"
version = "1.0.3"
description = ""
authors = ["Daniel Schweigert <dan.schweigert@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
psycopg = "^3.1.2"
pytest-cov = "^3.0.0"
coverage-badge = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
pytest-postgresql = "^4.1.1"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
