[build-system]
requires = [
    "setuptools",
    # 4110 only:
    # "cython",
    # "numpy==1.21.*",
]
build-backend = "setuptools.build_meta"

[project]
version = "0.1.0"
requires-python = ">=3.7"
license = {text = "MIT License"}
name = "knutthol-oblig3"
description = "in3110 assignment3"
readme = "README.md"
dependencies = [
]


[project.scripts]
# instapy = "..."
