[tool.poetry]
name = "python-acache"
packages = [
    { include="acache", from="." }
]
version = "0.1.4"
description = "Async cache"
authors = ["Dmitrij Vinokour <dimfred.1337@web.de>"]
homepage = "https://github.com/Dimfred/acache"
repository = "https://github.com/Dimfred/acache.git"
license = "MIT"

readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
pytest-asyncio = "^0.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
