[build-system]
requires = ["setuptools>=61.0", "SQLAlchemy>=1.4"]
build-backend = "setuptools.build_meta"

[project]
name = "utils_nm"
version = "0.2.0"
authors = [
  { name="Nikola Maksimovic", email="nikola.maksimovic@outlook.com" },
]
description = "Package for personal utility operations"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/NikoMak/utils_nm"
