# Formatters

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
lines_after_imports = 2
skip_glob = ['venv*']

[tool.black]
line-length = 79
target-version = ['py310']
include = '\.py$'
exclude = '''
/(
    \.git
  | \.venv.*
  | __pycache__
  | venv.*
  | build
  | dist
)/
'''


# Poetry

[tool.poetry]
name = "comlink"
version = "0.1.0"
description = "Send and receive messages by using SQS queues."
authors = ["Artem Fedotov"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "comlink" },
]

homepage = "https://github.com/art1415926535/comlink"
repository = "https://github.com/art1415926535/comlink"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/art1415926535/comlink/issues"
"Change Log" = "https://github.com/art1415926535/comlink/releases"

[tool.poetry.dependencies]
python = "^3.10"
aiobotocore = "^2.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1"
pytest-asyncio = "^0.19.0"
black = "^22.8.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


# Tests

[tool.pytest.ini_options]
asyncio_mode = "auto"
