[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"

[project]
name = "aioring"
version = "0.0.3"
description = "Asynchronous I/O ring"
readme = "README.md"
license = {file = "LICENSE"}
