[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "Wolvesburg"
version = "3.2.1"
authors = [
  { name="Pigly3", email="spot@wolvesburg.com" },
]
description = "Edit .wolvesburg files"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Pigly3/wolvesburg"
"Bug Tracker" = "https://github.com/Pigly3/wolvesburg/issues"