[tool.poetry]
name = "beam-sdk"
version = "0.1.7"
description = ""
authors = ["luke lombardi <luke@slai.io>"]
packages = [
    { include = "beam" },
    { include = "beam/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.8"
mypy = "^0.971"
packaging = "^21.3"
marshmallow = "^3.18.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
