[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "vina2vi"
version = "0.0.2"
dependencies = [
    #"tensorflow",
    #'importlib-metadata; python_version<"3.8"',
]
readme = "README.md"

