[tool.poetry]
name = "aspyco"
version = "1.0"
description = "Upload and start your custom payloads remotely !"
license = "GPL-3.0-only"
authors = ["Processus Thief <aspyco@thiefin.fr>"]
maintainers = [
    "Processus Thief <aspyco@thiefin.fr>"
]
readme = "README.md"
homepage = "https://github.com/Processus-Thief/Aspyco"
repository = "https://github.com/Processus-Thief/Aspyco"
documentation = "https://github.com/Processus-Thief/Aspyco"
keywords = ["aspyco", "windows", "psexec", "smbexec", "reverse", "shell", "credentials"]
packages = [
    { include = "src/*.py" }
]


[tool.poetry.dependencies]
python = "^3.6"
impacket = "^0.10.0"

[tool.poetry.scripts]
aspyco = "src.aspyco:main"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/Processus-Thief/Aspyco/issues"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"